use_gpu: False
input_image_path: 'path/to/your/image.jpg'
data_directory: 'data'
image_processing_steps:
  - 'sharpening'
  - 'contrast'
  - 'denoising'
model_path: null # 사용할 모델 파일 경로 (null이면 기본 모델 사용)
models_to_evaluate:
  - 'easyocr'
  - 'tesseract'
output_directory: 'evaluation_results'
metrics:
  - 'accuracy'
  - 'wer'
  - 'cer'
  - 'recall'
  - 'precision'
language: 'ko' # Korean language setting for OCR
# Add other configuration settings here, e.g., image directories 