use_gpu: False
input_image_path: 'path/to/your/image.jpg'
image_processing_steps: [] # 이미지 처리 단계를 리스트로 명시 (예: ['sharpening', 'denoising'])
model_path: null # 사용할 모델 파일 경로 (null이면 기본 모델 사용)
# Add other configuration settings here, e.g., image directories 